services:
  keto:
    image: oryd/keto:latest
    ports:
      - "4466:4466"
      - "4467:4467"
    volumes:
      - ./config:/home/ory
    command: serve -c /home/ory/keto.yml
    environment:
      - LOG_LEAK_SENSITIVE_VALUES=true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4466/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
